/* eslint-disable @next/next/no-img-element */
import moment from "moment";
import Head from "next/head";
import Footer from "../../components/Footer";
import FormCheckout from "../../components/FormCheckout";
import Navbar from "../../components/Navbar";
import { getData } from "../../utils/fetchData";
import { formatDate } from "../../utils/formatDate";
import { useEffect, useState } from "react";
import Button from "../../components/Button";
import Link from "next/link";
import { useRouter } from "next/router";
import Cookies from "js-cookie";
import FormSettings from "../../components/FormSettings";
import jwt_decode from "jwt-decode";

export default function Dashboard({ data }) {
  const router = useRouter();
  const [user, setUser] = useState({});

  useEffect(() => {
    const token = Cookies.get("token");

    const decode = jwt_decode(token);
    setUser({ ...decode });
    if (!token) {
      router.push("/");
    }
  }, [router]);

  return (
    <>
      <Head>
        <title>Tokosidia || Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="bg-navy">
        <Navbar />
      </section>

      <section className="bg-navy">
        <div className="dashboard-menu container d-flex flex-row justify-content-between">
          <div className="side-menu-btn p-4">
            <div className="side-profile mb-4 justify-content-around">
              <img
                className="rounded-circle"
                src={"/images/details-image.png"}
                width={100}
                height={100}
                alt="tokosidia"
              />
              <div className="side-profile-info ml-2 mt-3">
                <h3>acep nurman</h3>
              </div>
            </div>
            <div className="side-btn d-flex flex-column">
              <Link href={"/dashboard"} className="btn-side-group d-flex">
                <Button variant={"btn-side-menu"}>Dasboard</Button>
              </Link>
              <Link href={"/setting"} className="btn-side-group d-flex">
                <Button variant={"btn-side-menu bg-primary text-white"}>
                  Setting
                </Button>
              </Link>
            </div>
          </div>
          <div className="side-menu-info p-4">
            <div className="header-side-menu">
              <h2 className="mb-3 mt-4">Akun</h2>
            </div>
            <div className="trx-side-menu p-3">
              <FormSettings user={user} />
            </div>
          </div>
        </div>
      </section>
      <Footer />
    </>
  );
}

// export async function getServerSideProps(context) {
//   const req = await getData(`/api/v1/orders`, {}, context.req.cookies.token);

//   const res = req.data;

//   return {
//     props: { data: res },
//   };
// }
