/* eslint-disable @next/next/no-img-element */
import { useEffect, useState } from "react";
import { useRouter } from "next/router";
import Link from "next/link";
import Cookies from "js-cookie";
import jwt_decode from "jwt-decode";
import Head from "next/head";
import Navbar from "../../../components/Navbar";
import Button from "../../../components/Button";
import FormCreate from "./FormCreate";
import Footer from "../../../components/Footer";
import { getData } from "../../../utils/fetchData";

export default function Dashboard({ data, token }) {
  const router = useRouter();
  const [user, setUser] = useState({});

  useEffect(() => {
    const token = Cookies.get("token");

    const decode = jwt_decode(token);
    setUser(decode);
    if (!token) {
      router.push("/");
    }
  }, [router]);

  return (
    <>
      <Head>
        <title>Tokosidia || Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="bg-navy">
        <Navbar />
      </section>

      <section className="bg-navy">
        <div className="dashboard-menu container d-flex flex-row justify-content-between">
          <div className="side-menu-btn p-4">
            <div className="side-profile mb-4 justify-content-around">
              <img
                className="rounded-circle"
                src={"/images/details-image.png"}
                width={100}
                height={100}
                alt="tokosidia"
              />
              <div className="side-profile-info ml-2 mt-3">
                <h3>acep nurman</h3>
              </div>
            </div>
            {user.role !== "customer" ? (
              <div className="side-btn d-flex flex-column">
                <Link href={"/dashboard"} className="btn-side-group d-flex">
                  <Button variant={"btn-side-menu"}>Dashboard</Button>
                </Link>
                <Link href={"/category"} className="btn-side-group d-flex">
                  <Button variant={"btn-side-menu"}>Category</Button>
                </Link>
                <Link href={"/product"} className="btn-side-group d-flex">
                  <Button variant={"btn-side-menu bg-primary text-white"}>
                    Product
                  </Button>
                </Link>
              </div>
            ) : (
              <div className="side-btn d-flex flex-column">
                <Link href={"/dashboard"} className="btn-side-group d-flex">
                  <Button variant={"btn-side-menu bg-primary text-white"}>
                    Dasboard
                  </Button>
                </Link>
                <Link href={"/setting"} className="btn-side-group d-flex">
                  <Button variant={"btn-side-menu"}>Setting</Button>
                </Link>
              </div>
            )}
          </div>
          <FormCreate token={token} />
        </div>
      </section>
      <Footer />
    </>
  );
}

export async function getServerSideProps(context) {
  const req = await getData(
    `/api/v1/categories`,
    {},
    context.req.cookies.token
  );

  const res = req.data;

  return {
    props: { data: res, token: context.req.cookies.token },
  };
}
