import Head from "next/head";
import CardEvent from "../components/CardEvent";
import Footer from "../components/Footer";
import Header from "../components/Header";
import { getData } from "../utils/fetchData";

export default function Home({ data }) {
  return (
    <>
      <Head>
        <title>Tokosidia || Landing Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <CardEvent
        data={data}
        title="Belanja hanya ada disini"
        subTitle="Whats new Today"
      />
      <Footer />
    </>
  );
}

export async function getServerSideProps(context) {
  const res = await getData("/api/v1/product");

  return {
    props: { data: res.data }, // will be passed to the page component as props
  };
}
