import Head from "next/head";
import React from "react";
import FormSignup from "../components/FormSignup";
import Navbar from "../components/Navbar";
import Brand from "../components/Brand";

const Signup = () => {
  return (
    <>
      <Head>
        <title>Tokosidia || Signup</title>
        <meta name="description" content="Generated by created next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="bg-navy">
        <Navbar />
      </section>

      <section className="login header bg-navy">
        <div className="container">
          <div className="row row-cols-md-12 row-cols-1 d-flex justify-content-center align-items-center hero">
            <div className="col-md-6">
              <div className="hero-headline text-start">
                Expand Your <br className="d-none d-md-block" />
                Life Style & Hobby
              </div>

              <p className="hero-paragraph text-start">
                Kami menyediakan berbagai perlengkapan terbaik{" "}
                <br className="d-none d-lg-block" />
                untuk memenuhi kebetuhan anda
              </p>
            </div>
            <div className="col-md-6">
              <FormSignup />
            </div>
          </div>
        </div>
      </section>

      <Brand className="pt-0 bg-navy" />
    </>
  );
};

export default Signup;

export async function getServerSideProps(context) {
  const { token } = context.req.cookies;

  if (token) {
    return {
      redirect: {
        destination: "/",
        permanent: false,
      },
    };
  }

  return {
    props: {},
  };
}
