import React from "react";
import Head from "next/head";
import FormSignin from "../components/FormSignin";
import Navbar from "../components/Navbar";
import Brand from "../components/Brand";

const Signin = () => {
  return (
    <>
      <Head>
        <title>Tokosidia || Landing Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="bg-navy">
        <Navbar />
      </section>
      <section className="login header bg-navy">
        <div className="container">
          <div className="d-flex flex-column align-items-center hero gap-5">
            <div>
              <div className="hero-headline text-start">Signin</div>
            </div>
            <FormSignin />
          </div>
        </div>
      </section>
    </>
  );
};

export default Signin;

export async function getServerSideProps(context) {
  const { token } = context.req.cookies;

  if (token) {
    return {
      redirect: {
        destination: "/",
        permanent: false,
      },
    };
  }

  return {
    props: {},
  };
}
